# Generated by Django 5.2 on 2025-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exp_multiplier', models.FloatField()),
                ('rooms_before_boss', models.IntegerField()),
                ('bonus_exp_chest', models.IntegerField(default=5)),
                ('bonus_exp_buff', models.IntegerField(default=3)),
                ('hp_multiplier', models.FloatField(default=1.0)),
                ('attack_multiplier', models.FloatField(default=1.0)),
                ('defense_multiplier', models.FloatField(default=1.0)),
                ('crit_multiplier', models.FloatField(default=1.0)),
            ],
        ),
    ]
