# Generated by Django 5.2 on 2025-04-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dungeon', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('skill_points', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('base_attack', models.IntegerField(default=10)),
                ('armor', models.IntegerField(default=5)),
                ('current_room', models.IntegerField(default=1)),
                ('is_alive', models.BooleanField(default=True)),
                ('archetype', models.CharField(choices=[('brave', 'Бесстрашный'), ('sarcastic', 'Саркастичный'), ('dark', 'Мрачный')], default='brave', max_length=20)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dungeon.dungeondifficulty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
