# Generated by Django 5.2 on 2025-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeondifficulty',
            name='bonus_exp_buff',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='dungeondifficulty',
            name='bonus_exp_chest',
            field=models.IntegerField(default=5),
        ),
    ]
