# Generated by Django 5.2 on 2025-04-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('skeleton', 'Скелет'), ('goblin', 'Гоблин'), ('orc', 'Орк'), ('undead', 'Нежить'), ('werewolf', 'Оборотень'), ('mage', 'Маг'), ('dragon', 'Дракон')], max_length=100)),
                ('is_boss', models.BooleanField(default=False)),
                ('base_hp', models.IntegerField(default=50)),
                ('base_attack', models.IntegerField(default=10)),
                ('base_defense', models.IntegerField(default=5)),
                ('base_crit_chance', models.FloatField(default=0.05)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_multiplier', models.FloatField(default=1.0)),
                ('attack_multiplier', models.FloatField(default=1.0)),
                ('defense_multiplier', models.FloatField(default=1.0)),
                ('crit_bonus', models.FloatField(default=0.0)),
                ('exp_reward', models.IntegerField(default=10)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeon.dungeondifficulty')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='enemies.enemy')),
            ],
        ),
    ]
