# Generated by Django 5.2 on 2025-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemystats',
            name='exp_reward',
            field=models.IntegerField(default=10),
        ),
    ]
