# Generated by Django 5.2 on 2025-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuffDebuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('effect_type', models.CharField(choices=[('buff', 'Баф'), ('debuff', 'Дебафф')], max_length=10)),
                ('attribute', models.CharField(choices=[('attack', 'Атака'), ('defense', 'Защита'), ('hp', 'Здоровье'), ('crit_chance', 'Шанс крита')], max_length=20)),
                ('value', models.FloatField(help_text='1.2 = +20%, 0.8 = -20%')),
                ('duration', models.IntegerField(help_text='На сколько ходов эффект действует')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
